apiVersion: apps/v1 #

kind: Deployment #deployment / service

metadata: #deployment metadata
  name: hello-world
  labels:
    app: hello-world


spec: #specifications
  replicas: 3 #count of pods
  
  selector:
    matchLabels:
      app: hello-world

  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: hello-world:latest
        stdin: true #console log
        tty: true #console
        # ports:
        # - containerPort: 80
