apiVersion: apps/v1

kind: Deployment

metadata:
  name: imt2018073-calculator
  labels:
    app: calculator


spec:
  replicas: 3
  
  selector:
    matchLabels:
      app: calculator

  template:
    metadata:
      labels:
        app: calculator

    spec:
      containers:
      - name: calculator
        image: imt2018073/calculator:latest
        ports:
        - containerPort: 80
